// <auto-generated />
using System;
using FlowEngine.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlowEngine.Infrastructure.Migrations
{
    [DbContext(typeof(FlowEngineDbContext))]
    [Migration("20260618140320_AddCredentials")]
    partial class AddCredentials
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("FlowEngine.Infrastructure.Persistence.Entities.CredentialEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id")
                        .HasComment("主键");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasComment("创建时间");

                    b.Property<string>("DataJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("data")
                        .HasComment("加密字段数据 JSON");

                    b.Property<string>("KeyVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("key_version")
                        .HasComment("密钥版本");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .HasComment("凭据名称");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("type")
                        .HasComment("凭据类型");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasComment("更新时间");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Type");

                    b.ToTable("credentials", null, t =>
                        {
                            t.HasComment("凭据定义");
                        });
                });

            modelBuilder.Entity("FlowEngine.Infrastructure.Persistence.Entities.ExecutionRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id")
                        .HasComment("主键");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at")
                        .HasComment("完成时间");

                    b.Property<string>("NodeRecordsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("node_records")
                        .HasComment("节点执行记录列表 JSON");

                    b.Property<Guid?>("ParentExecutionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("parent_execution_id")
                        .HasComment("父执行 ID");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at")
                        .HasComment("开始时间");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status")
                        .HasComment("执行状态");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("workflow_definition_id")
                        .HasComment("工作流定义 ID");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("WorkflowDefinitionId");

                    b.ToTable("execution_records", t =>
                        {
                            t.HasComment("执行记录");
                        });
                });

            modelBuilder.Entity("FlowEngine.Infrastructure.Persistence.Entities.NodeExecutionRecordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id")
                        .HasComment("主键");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at")
                        .HasComment("完成时间");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("execution_id")
                        .HasComment("执行 ID");

                    b.Property<string>("InputsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("inputs")
                        .HasComment("输入数据批次映射 JSON");

                    b.Property<Guid>("NodeDefinitionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("node_definition_id")
                        .HasComment("节点定义 ID");

                    b.Property<string>("OutputJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("output")
                        .HasComment("节点执行结果 JSON");

                    b.Property<string>("RawParametersJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("raw_parameters")
                        .HasComment("原始参数映射 JSON");

                    b.Property<string>("ResolvedParametersJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("resolved_parameters")
                        .HasComment("解析后的参数映射 JSON");

                    b.Property<int>("RunIndex")
                        .HasColumnType("INTEGER")
                        .HasColumnName("run_index")
                        .HasComment("运行索引");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at")
                        .HasComment("开始时间");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionId");

                    b.ToTable("node_execution_records", t =>
                        {
                            t.HasComment("节点执行记录");
                        });
                });

            modelBuilder.Entity("FlowEngine.Infrastructure.Persistence.Entities.WorkflowDefinitionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id")
                        .HasComment("主键");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version")
                        .HasComment("版本号");

                    b.Property<string>("ConnectionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("connections")
                        .HasComment("连接列表 JSON");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasComment("创建时间");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by")
                        .HasComment("创建人");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active")
                        .HasComment("是否激活");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .HasComment("工作流名称");

                    b.Property<string>("NodesJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nodes")
                        .HasComment("节点实例列表 JSON");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id")
                        .HasComment("项目 ID");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at")
                        .HasComment("更新时间");

                    b.HasKey("Id", "Version");

                    b.HasIndex("Name");

                    b.ToTable("workflow_definitions", t =>
                        {
                            t.HasComment("工作流定义");
                        });
                });

            modelBuilder.Entity("FlowEngine.Infrastructure.Persistence.Entities.NodeExecutionRecordEntity", b =>
                {
                    b.HasOne("FlowEngine.Infrastructure.Persistence.Entities.ExecutionRecordEntity", "Execution")
                        .WithMany("NodeExecutions")
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Execution");
                });

            modelBuilder.Entity("FlowEngine.Infrastructure.Persistence.Entities.ExecutionRecordEntity", b =>
                {
                    b.Navigation("NodeExecutions");
                });
#pragma warning restore 612, 618
        }
    }
}
