// <auto-generated />
using System;
using FlowEngine.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlowEngine.Migrations.Migrations.Sqlite
{
    [DbContext(typeof(FlowEngineDbContext))]
    [Migration("20260727031510_UnifyProjectCreatedByToString")]
    partial class UnifyProjectCreatedByToString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("FlowEngine.Core.Entities.Credential", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("创建时间");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("data")
                        .HasComment("加密字段数据映射");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER")
                        .HasComment("是否删除");

                    b.Property<string>("KeyVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("key_version")
                        .HasComment("密钥版本");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .HasComment("凭据名称");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id")
                        .HasComment("项目 ID");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("type")
                        .HasComment("凭据类型");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("最后更新时间");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_credentials_name_null_project")
                        .HasFilter("\"project_id\" IS NULL");

                    b.HasIndex("Name", "ProjectId")
                        .IsUnique()
                        .HasDatabaseName("IX_credentials_name_project_id_notnull")
                        .HasFilter("\"project_id\" IS NOT NULL");

                    b.ToTable("credentials", "flow", t =>
                        {
                            t.HasComment("凭据定义");
                        });
                });

            modelBuilder.Entity("FlowEngine.Core.Entities.ExecutionDedup", b =>
                {
                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("idempotency_key")
                        .HasComment("幂等键");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at")
                        .HasComment("创建时间");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("execution_id")
                        .HasComment("执行记录 ID");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at")
                        .HasComment("过期时间");

                    b.HasKey("IdempotencyKey");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.ToTable("execution_dedup", "flow", t =>
                        {
                            t.HasComment("执行幂等去重表");
                        });
                });

            modelBuilder.Entity("FlowEngine.Core.Entities.ExecutionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at")
                        .HasComment("完成时间");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("创建时间");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER")
                        .HasComment("是否删除");

                    b.Property<string>("NodeRecords")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("node_records")
                        .HasComment("节点执行记录列表");

                    b.Property<Guid?>("ParentExecutionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("parent_execution_id")
                        .HasComment("父执行 ID");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id")
                        .HasComment("项目 ID");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at")
                        .HasComment("开始时间");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status")
                        .HasComment("执行状态");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("最后更新时间");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("workflow_definition_id")
                        .HasComment("工作流定义 ID");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("Status", "CompletedAt");

                    b.HasIndex("WorkflowDefinitionId", "StartedAt");

                    b.ToTable("execution_records", "flow", t =>
                        {
                            t.HasComment("执行记录");
                        });
                });

            modelBuilder.Entity("FlowEngine.Core.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("创建时间");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by")
                        .HasComment("创建人");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER")
                        .HasComment("是否删除");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("description")
                        .HasComment("项目描述");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .HasComment("项目名称");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("最后更新时间");

                    b.HasKey("Id");

                    b.ToTable("projects", "flow", t =>
                        {
                            t.HasComment("项目");
                        });
                });

            modelBuilder.Entity("FlowEngine.Core.Entities.StoredFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentType")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasColumnName("content_type")
                        .HasComment("MIME 类型");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("创建时间");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER")
                        .HasComment("是否删除");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_name")
                        .HasComment("文件名");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id")
                        .HasComment("所属项目");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER")
                        .HasColumnName("size")
                        .HasComment("文件大小");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .HasColumnName("storage_path")
                        .HasComment("存储路径");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("最后更新时间");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("TEXT")
                        .HasColumnName("uploaded_by")
                        .HasComment("上传者");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("stored_files", "flow", t =>
                        {
                            t.HasComment("存储文件");
                        });
                });

            modelBuilder.Entity("FlowEngine.Core.Entities.Trigger", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("创建时间");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER")
                        .HasComment("是否删除");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active")
                        .HasComment("是否激活");

                    b.Property<DateTime?>("LastTriggeredAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_triggered_at")
                        .HasComment("最后触发时间");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .HasComment("触发器名称");

                    b.Property<DateTime?>("NextTriggerAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_trigger_at")
                        .HasComment("下次触发时间");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id")
                        .HasComment("项目 ID");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("settings")
                        .HasComment("触发器配置");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type")
                        .HasComment("触发器类型");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("最后更新时间");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("workflow_definition_id")
                        .HasComment("关联工作流定义 ID");

                    b.Property<int>("WorkflowVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("workflow_version")
                        .HasComment("工作流版本号");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("WorkflowDefinitionId");

                    b.ToTable("triggers", t =>
                        {
                            t.HasComment("触发器");
                        });
                });

            modelBuilder.Entity("FlowEngine.Core.Entities.WebhookRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("AllowedIps")
                        .HasColumnType("TEXT")
                        .HasColumnName("allowed_ips")
                        .HasComment("IP 白名单 JSON");

                    b.PrimitiveCollection<string>("AllowedOrigins")
                        .HasColumnType("TEXT")
                        .HasColumnName("allowed_origins")
                        .HasComment("来源域白名单 JSON");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("创建时间");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER")
                        .HasComment("是否删除");

                    b.Property<bool>("IsStatic")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_static")
                        .HasComment("是否静态路由");

                    b.Property<bool>("IsSync")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_sync")
                        .HasComment("是否同步响应");

                    b.Property<int>("MaxWaitSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_wait_seconds")
                        .HasComment("同步响应最大等待时间（秒）");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("method")
                        .HasComment("HTTP 方法");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("path")
                        .HasComment("Webhook 路径");

                    b.Property<string>("Secret")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("secret")
                        .HasComment("签名密钥");

                    b.Property<Guid>("TriggerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("trigger_id")
                        .HasComment("触发器 ID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("最后更新时间");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("workflow_definition_id")
                        .HasComment("关联工作流定义 ID");

                    b.HasKey("Id");

                    b.ToTable("webhook_routes", t =>
                        {
                            t.HasComment("Webhook 路由");
                        });
                });

            modelBuilder.Entity("FlowEngine.Core.Entities.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Connections")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("connections")
                        .HasComment("连接列表");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("创建时间");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by")
                        .HasComment("创建人");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER")
                        .HasComment("是否删除");

                    b.Property<string>("Diff")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("diff")
                        .HasComment("modify 草稿的结构化差异");

                    b.Property<int?>("DraftStatus")
                        .HasColumnType("INTEGER")
                        .HasColumnName("draft_status")
                        .HasComment("草稿审查状态：待审查/已拒绝/已确认");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active")
                        .HasComment("是否激活");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .HasComment("工作流名称");

                    b.Property<string>("Nodes")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("nodes")
                        .HasComment("节点实例列表");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id")
                        .HasComment("项目 ID");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("rejection_reason")
                        .HasComment("拒绝理由");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source")
                        .HasComment("工作流来源：人工创建或 AI 生成");

                    b.Property<string>("StyleSettings")
                        .HasColumnType("json")
                        .HasColumnName("style_settings")
                        .HasComment("样式设置");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("最后更新时间");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version")
                        .HasComment("版本号");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("workflows", "flow", t =>
                        {
                            t.HasComment("工作流定义");
                        });
                });

            modelBuilder.Entity("FlowEngine.Core.Entities.WorkflowCredentialUsage", b =>
                {
                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("TEXT")
                        .HasComment("所属工作流 ID");

                    b.Property<Guid>("CredentialId")
                        .HasColumnType("TEXT")
                        .HasComment("被引用凭据 ID");

                    b.Property<string>("NodeId")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasComment("引用该凭据的节点 ID（工作流级引用时为空字符串）");

                    b.Property<string>("WorkflowName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasComment("所属工作流名称（冗余存储，便于删除凭据时直接展示引用方，无需回查工作流表）");

                    b.HasKey("WorkflowId", "CredentialId", "NodeId");

                    b.HasIndex("CredentialId");

                    b.ToTable("workflow_credential_usages", "flow", t =>
                        {
                            t.HasComment("工作流→凭据引用关系（归一化关联表），用于删除凭据时快速定位引用方");
                        });
                });

            modelBuilder.Entity("FlowEngine.Core.Identity.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("创建时间");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER")
                        .HasComment("是否删除");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("expires_at")
                        .HasComment("过期时间");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("key_hash")
                        .HasComment("完整 Key 的哈希值");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .HasComment("令牌名称");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("prefix")
                        .HasComment("Key 前缀");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("revoked_at")
                        .HasComment("吊销时间");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("最后更新时间");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("user_id")
                        .HasComment("所属用户 ID");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("api_keys", "flow", t =>
                        {
                            t.HasComment("API Key");
                        });
                });

            modelBuilder.Entity("FlowEngine.Core.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("创建时间");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER")
                        .HasComment("是否删除");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasComment("显示名称");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasComment("邮箱地址");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasComment("是否激活");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasComment("密码哈希值");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("最后更新时间");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasComment("用户名");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", t =>
                        {
                            t.HasComment("用户");
                        });
                });

            modelBuilder.Entity("FlowEngine.Core.Identity.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("创建时间");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER")
                        .HasComment("是否删除");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasComment("角色名称");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("最后更新时间");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasComment("用户 ID");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Role")
                        .IsUnique();

                    b.ToTable("user_roles", t =>
                        {
                            t.HasComment("用户角色");
                        });
                });

            modelBuilder.Entity("FlowEngine.Core.Identity.ApiKey", b =>
                {
                    b.HasOne("FlowEngine.Core.Identity.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
