// <auto-generated />
using System;
using FlowEngine.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlowEngine.Migrations.Migrations.Sqlite
{
    [DbContext(typeof(FlowEngineDbContext))]
    partial class FlowEngineDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("FlowEngine.Core.Entities.Credential", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("创建时间");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER")
                        .HasComment("是否删除");

                    b.Property<string>("KeyVersion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("最后更新时间");

                    b.HasKey("Id");

                    b.ToTable("Credentials");
                });

            modelBuilder.Entity("FlowEngine.Core.Entities.ExecutionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("completed_at")
                        .HasComment("完成时间");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("创建时间");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER")
                        .HasComment("是否删除");

                    b.Property<string>("NodeRecords")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("node_records")
                        .HasComment("节点执行记录列表");

                    b.Property<Guid?>("ParentExecutionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("parent_execution_id")
                        .HasComment("父执行 ID");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("started_at")
                        .HasComment("开始时间");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status")
                        .HasComment("执行状态");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("最后更新时间");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("workflow_definition_id")
                        .HasComment("工作流定义 ID");

                    b.HasKey("Id");

                    b.ToTable("execution_records", "flow", t =>
                        {
                            t.HasComment("执行记录");
                        });
                });

            modelBuilder.Entity("FlowEngine.Core.Entities.Trigger", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("创建时间");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER")
                        .HasComment("是否删除");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active")
                        .HasComment("是否激活");

                    b.Property<DateTime?>("LastTriggeredAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_triggered_at")
                        .HasComment("最后触发时间");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .HasComment("触发器名称");

                    b.Property<DateTime?>("NextTriggerAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("next_trigger_at")
                        .HasComment("下次触发时间");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("settings")
                        .HasComment("触发器配置");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasColumnName("type")
                        .HasComment("触发器类型");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("最后更新时间");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("workflow_definition_id")
                        .HasComment("关联工作流定义 ID");

                    b.Property<int>("WorkflowVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("workflow_version")
                        .HasComment("工作流版本号");

                    b.HasKey("Id");

                    b.ToTable("triggers", t =>
                        {
                            t.HasComment("触发器");
                        });
                });

            modelBuilder.Entity("FlowEngine.Core.Entities.WebhookRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("AllowedIps")
                        .HasColumnType("TEXT")
                        .HasColumnName("allowed_ips")
                        .HasComment("IP 白名单 JSON");

                    b.PrimitiveCollection<string>("AllowedOrigins")
                        .HasColumnType("TEXT")
                        .HasColumnName("allowed_origins")
                        .HasComment("来源域白名单 JSON");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("创建时间");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER")
                        .HasComment("是否删除");

                    b.Property<bool>("IsStatic")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_static")
                        .HasComment("是否静态路由");

                    b.Property<bool>("IsSync")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_sync")
                        .HasComment("是否同步响应");

                    b.Property<int>("MaxWaitSeconds")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_wait_seconds")
                        .HasComment("同步响应最大等待时间（秒）");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("method")
                        .HasComment("HTTP 方法");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("path")
                        .HasComment("Webhook 路径");

                    b.Property<string>("Secret")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("secret")
                        .HasComment("签名密钥");

                    b.Property<Guid>("TriggerId")
                        .HasColumnType("TEXT")
                        .HasColumnName("trigger_id")
                        .HasComment("触发器 ID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("最后更新时间");

                    b.Property<Guid>("WorkflowDefinitionId")
                        .HasColumnType("TEXT")
                        .HasColumnName("workflow_definition_id")
                        .HasComment("关联工作流定义 ID");

                    b.HasKey("Id");

                    b.ToTable("webhook_routes", t =>
                        {
                            t.HasComment("Webhook 路由");
                        });
                });

            modelBuilder.Entity("FlowEngine.Core.Entities.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("创建时间");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by")
                        .HasComment("创建人");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER")
                        .HasComment("是否删除");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active")
                        .HasComment("是否激活");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("name")
                        .HasComment("工作流名称");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id")
                        .HasComment("项目 ID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("最后更新时间");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version")
                        .HasComment("版本号");

                    b.HasKey("Id");

                    b.ToTable("workflows", "flow", t =>
                        {
                            t.HasComment("工作流定义");
                        });
                });

            modelBuilder.Entity("FlowEngine.Core.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("创建时间");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER")
                        .HasComment("是否删除");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasComment("显示名称");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT")
                        .HasComment("邮箱地址");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasComment("是否激活");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasComment("密码哈希值");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("最后更新时间");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT")
                        .HasComment("用户名");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", t =>
                        {
                            t.HasComment("用户");
                        });
                });

            modelBuilder.Entity("FlowEngine.Core.Identity.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasMaxLength(36)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("创建时间");

                    b.Property<bool>("Deleted")
                        .HasColumnType("INTEGER")
                        .HasComment("是否删除");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasComment("角色名称");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasComment("最后更新时间");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT")
                        .HasComment("用户 ID");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Role")
                        .IsUnique();

                    b.ToTable("user_roles", t =>
                        {
                            t.HasComment("用户角色");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
