import {
  Globe,
  GitBranch,
  Code,
  Database,
  FileText,
  Mail,
  MessageSquare,
  Calendar,
  Clock,
  Settings,
  Play,
  Layers,
  Box,
  Bot,
  Brain,
  Wrench,
  Webhook,
  Search,
  Terminal,
  Calculator,
  ArrowUpDown,
  Filter,
  Hash,
  Pause,
  Repeat,
  Merge,
  Pencil,
  HardDrive,
  FileEdit,
  LayoutList,
  AlertTriangle,
  Table,
  FileSearch,
  StickyNote,
  Circle,
  List,
  AlertCircle,
  Lock,
  Minimize2,
  Scissors,
  Key,
  ShieldCheck,
  type LucideIcon,
} from 'lucide-react';

const iconMap: Record<string, LucideIcon> = {
  globe: Globe,
  'git-branch': GitBranch,
  code: Code,
  database: Database,
  'file-text': FileText,
  mail: Mail,
  email: Mail,
  'message-square': MessageSquare,
  chat: MessageSquare,
  calendar: Calendar,
  clock: Clock,
  settings: Settings,
  play: Play,
  layers: Layers,
  box: Box,
  bot: Bot,
  robot: Bot,
  brain: Brain,
  wrench: Wrench,
  webhook: Webhook,
  shuffle: GitBranch,
  search: Search,
  terminal: Terminal,
  calculator: Calculator,
  sort: ArrowUpDown,
  filter: Filter,
  'filter-1': Filter,
  hash: Hash,
  pause: Pause,
  repeat: Repeat,
  merge: Merge,
  edit: Pencil,
  redis: Database,
  storage: HardDrive,
  mongo: Database,
  'file-write': FileEdit,
  structured: LayoutList,
  alert: AlertTriangle,
  spreadsheet: Table,
  'file-read': FileSearch,
  note: StickyNote,
  noop: Circle,
  list: List,
  error: AlertCircle,
  lock: Lock,
  compress: Minimize2,
  split: Scissors,
  key: Key,
  'shield-check': ShieldCheck,
};

interface NodeIconProps {
  icon: string;
  size?: number;
  className?: string;
  /** 图标颜色（stroke），通常传入节点分类色 */
  color?: string;
}

export function NodeIcon({ icon, size = 16, className, color }: NodeIconProps) {
  const Icon = iconMap[icon.toLowerCase()] ?? Box;
  return <Icon size={size} className={className} color={color} />;
}