<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FlowEngine.Core\FlowEngine.Core.csproj" />
    <ProjectReference Include="..\FlowEngine.Runtime\FlowEngine.Runtime.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.9.2" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.9.2" />
    <PackageReference Include="Mapster" Version="7.4.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="FlowEngine.Application.Tests" />
    <InternalsVisibleTo Include="FlowEngine.Host" />
  </ItemGroup>

</Project>
